server:
  port: 8091
spring:
  application:
    name: consumer
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:20000/eureka
  instance:
    prefer-ip-address: true # 当其它服务获取地址时提供ip而不是hostname
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 1000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMillisecond: 6000 # 设置hystrix的超时时间为6000ms
#  user-service:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMillisecond: 6000 # 设置hystrix的超时时间为6000ms
logging:
  level:
    com.zshuai: debug